version: '3'
services:
  similarity-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: similarity_search_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"


